version: '3'

services:
  mysql1:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=mytestdb
      - MYSQL_USER=admin
      - MYSQL_HOST=127.0.0.1
      - MYSQL_PASSWORD=abc123
    ports:
      - 3306:3306
  ktor-run:
    image: ktor-app
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql1
